<?php 
	// Adding Custom Fields...
	
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_57b943d543fda',
	'title' => 'Applications',
	'fields' => array (
		array (
			'key' => 'field_57b943dde95f2',
			'label' => 'Choose course or programme',
			'name' => 'choose_course_or_programme',
			'type' => 'page_link',
			'instructions' => 'Select the course or programmes that you would like to apply',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'summer_camp',
				1 => 'exchange_programmes',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'allow_archives' => 1,
			'multiple' => 0,
		),
		array (
			'key' => 'field_57b9442fe95f3',
			'label' => 'Name',
			'name' => 'name',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57b944a3e4552',
			'label' => 'Email',
			'name' => 'email',
			'type' => 'email',
			'instructions' => 'Enter your email address',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_57b944c1e4553',
			'label' => 'Phone Number',
			'name' => 'phone_number',
			'type' => 'number',
			'instructions' => 'Enter your phone number',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_57b944e0e4554',
			'label' => 'Mailing Address',
			'name' => 'mailing_address',
			'type' => 'textarea',
			'instructions' => 'Enter your permanent mailing address',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_57b94548e4555',
			'label' => 'Upload proposal',
			'name' => 'upload_proposal',
			'type' => 'file',
			'instructions' => 'Upload your proposal document here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'uploadedTo',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'application',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_57b93a06820f9',
	'title' => 'Exchange Programmes',
	'fields' => array (
		array (
			'key' => 'field_57b93a0687625',
			'label' => 'Exchange Programme General Information',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57b93a0687639',
			'label' => 'Programme Image',
			'name' => 'programme_image',
			'type' => 'image',
			'instructions' => 'Suggest an image to represent the programme. The image should not be copyright protected, and that you own the image. If you do not have an image to represent this programme, leave this blank for now.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'uploadedTo',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_57b93a068764a',
			'label' => 'Programme Title',
			'name' => 'programme_title',
			'type' => 'text',
			'instructions' => 'Enter the title of the programme',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57b93a068765c',
			'label' => 'Programme Description',
			'name' => 'programme_description',
			'type' => 'textarea',
			'instructions' => 'Enter programme description here',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array (
			'key' => 'field_57b93a068766d',
			'label' => 'Programme Content',
			'name' => 'programme_content',
			'type' => 'textarea',
			'instructions' => 'Provide a summary of the programme e.g. "This programme will cover subjects such as ...."',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_57b93a068767d',
			'label' => 'What\'s Included?',
			'name' => 'whats_included_programme',
			'type' => 'textarea',
			'instructions' => 'Add highlights of this programme e.g. "Visits: Terengganu - Rantau Abang and Dugong Island, Tour: Homestay and Kuala Lumpur City Tour".',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_57b93a068768e',
			'label' => 'Programme Duration',
			'name' => 'programme_duration',
			'type' => 'number',
			'instructions' => 'Enter the amount of days this programme will take, in numbers only e.g. \'13\'.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_57e1f367fa471',
			'label' => 'Credit Transfer',
			'name' => 'credit_transfer_ep',
			'type' => 'radio',
			'instructions' => 'Is credit transfer available for this programme?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Available' => 'Available',
				'Not Available' => 'Not Available',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'array',
		),
		array (
			'key' => 'field_57b93a06876a0',
			'label' => 'Programme Fee',
			'name' => '',
			'type' => 'tab',
			'instructions' => 'Enter the fee amount respectively',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57b93a06876b1',
			'label' => 'Partner-University Participants',
			'name' => 'partner-university_participants_ep',
			'type' => 'text',
			'instructions' => 'Enter the fee amount for participants from our partner-universities',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'e.g. 500 USD',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57b93a06876c2',
			'label' => 'NonPartner-University Participants',
			'name' => 'nonpartner-university_participants_ep',
			'type' => 'text',
			'instructions' => 'Enter the fee amount for participants from nonpartner-universities',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'e.g. 500 USD',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57b93a06876d3',
			'label' => 'Programme Itinerary',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57b93a06876e3',
			'label' => 'Programme Itinerary Details',
			'name' => 'course_itinerary_details_ep',
			'type' => 'repeater',
			'instructions' => 'Please enter details of the course, day by day.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add A New Day',
			'sub_fields' => array (
				array (
					'key' => 'field_57b93a069acf6',
					'label' => 'Day',
					'name' => 'day_ep',
					'type' => 'text',
					'instructions' => 'Label as \'Day 1\', \'Day 2\', \'Day3\'....',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Day',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_57b93a069ad0d',
					'label' => 'Activities',
					'name' => 'activities_ep',
					'type' => 'wysiwyg',
					'instructions' => 'List down the activities for this day',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'visual',
					'toolbar' => 'basic',
					'media_upload' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'exchange_programmes',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_57b93d5eea54c',
	'title' => 'Facilities and Services',
	'fields' => array (
		array (
			'key' => 'field_57b9429ce6505',
			'label' => 'Title of facility/service',
			'name' => 'title_of_facilityservice',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57b94304e6506',
			'label' => 'Description of facility/service',
			'name' => 'description_of_facilityservice',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'facilities',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_57b9024550b82',
	'title' => 'Programmes Offered',
	'fields' => array (
		array (
			'key' => 'field_57b90256ef593',
			'label' => 'Faculty\'s Name',
			'name' => 'facultys_name',
			'type' => 'text',
			'instructions' => 'Please provide the Faculty\'s full name',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57b902e6ef594',
			'label' => 'Programmes offered',
			'name' => 'programmes_offered',
			'type' => 'repeater',
			'instructions' => 'Add the programmes here',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_57b90495ef595',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add New Programme',
			'sub_fields' => array (
				array (
					'key' => 'field_57b90495ef595',
					'label' => 'Programme Title',
					'name' => 'programme_title',
					'type' => 'text',
					'instructions' => 'Add the title of the programme here',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_57b904ceef596',
					'label' => 'Programme URL',
					'name' => 'programme_url',
					'type' => 'url',
					'instructions' => 'Provide the related url for this programme, if available',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'programmes_offered',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_57b8fdceb3ded',
	'title' => 'Staffs',
	'fields' => array (
		array (
			'key' => 'field_57b8fe855ca33',
			'label' => 'Staff Type',
			'name' => 'staff_type',
			'type' => 'radio',
			'instructions' => 'Please choose the type of staff you are submitting.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'scm' => 'Steering Committee Member',
				'wcm' => 'Working Committee Member',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_57b8fddb5ca31',
			'label' => 'Profile Image',
			'name' => 'profile_image_staff',
			'type' => 'image',
			'instructions' => 'Upload an image. Should be at least 200x200 pixel.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_57b8fe4b5ca32',
			'label' => 'Name',
			'name' => 'name',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57b8ff245ca34',
			'label' => 'Email',
			'name' => 'email',
			'type' => 'email',
			'instructions' => 'Please provide an email address',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57b8fe855ca33',
						'operator' => '==',
						'value' => 'wcm',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_57b8ff9d5ca35',
			'label' => 'Phone Number',
			'name' => 'phone_number',
			'type' => 'number',
			'instructions' => 'Please provide a phone number',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57b8fe855ca33',
						'operator' => '==',
						'value' => 'wcm',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_57b9008a5ca36',
			'label' => 'Position',
			'name' => 'position',
			'type' => 'text',
			'instructions' => 'Please provide the role of this staff in this Mobility Unit',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'committee',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_57b92cdd175ac',
	'title' => 'Summer Camps',
	'fields' => array (
		array (
			'key' => 'field_57b933e62d6d9',
			'label' => 'Course General Information',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57b92e3737ad8',
			'label' => 'Course Image',
			'name' => 'course_image',
			'type' => 'image',
			'instructions' => 'Suggest an image to represent the course. The image should not be copyright protected, and that you own the image. If you do not have an image to represent this course, leave this blank for now.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'uploadedTo',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_57b92ce337ad6',
			'label' => 'Course Title',
			'name' => 'course_title',
			'type' => 'text',
			'instructions' => 'Enter the title of the course',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57b92e0937ad7',
			'label' => 'Course Description',
			'name' => 'course_description',
			'type' => 'textarea',
			'instructions' => 'Enter course description here',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array (
			'key' => 'field_57b92f2b37ad9',
			'label' => 'Course Content',
			'name' => 'course_content',
			'type' => 'textarea',
			'instructions' => 'Provide a summary of the course e.g. "This course will cover subjects such as ...."',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_57b9302537ada',
			'label' => 'What\'s Included?',
			'name' => 'whats_included',
			'type' => 'textarea',
			'instructions' => 'Add highlights of this course e.g. "Visits: Terengganu - Rantau Abang and Dugong Island, Tour: Homestay and Kuala Lumpur City Tour".',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_57b9321037adb',
			'label' => 'Duration',
			'name' => 'duration',
			'type' => 'number',
			'instructions' => 'Enter the amount of days this course will take, in numbers only e.g. \'13\'.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_57e1f241280e4',
			'label' => 'Credit Transfer',
			'name' => 'credit_transfer',
			'type' => 'radio',
			'instructions' => 'Choose whether credit transfer is available for this course, or not.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Available' => 'Available',
				'Not Available' => 'Not Available',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'array',
		),
		array (
			'key' => 'field_57b9326f37adc',
			'label' => 'Course Fee',
			'name' => '',
			'type' => 'tab',
			'instructions' => 'Enter the fee amount respectively',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57b9332a37add',
			'label' => 'Partner-University Participants',
			'name' => 'partner-university_participants',
			'type' => 'text',
			'instructions' => 'Enter the fee amount for participants from our partner-universities',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'e.g. 500 USD',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57b9337937ade',
			'label' => 'NonPartner-University Participants',
			'name' => 'nonpartner-university_participants',
			'type' => 'text',
			'instructions' => 'Enter the fee amount for participants from nonpartner-universities',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'e.g. 500 USD',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57b93492e9cfe',
			'label' => 'Course Itinerary',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57b934b2e9cff',
			'label' => 'Course Itinerary Details',
			'name' => 'course_itinerary_details',
			'type' => 'repeater',
			'instructions' => 'Please enter details of the course, day by day.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add A New Day',
			'sub_fields' => array (
				array (
					'key' => 'field_57b9350fe9d00',
					'label' => 'Day',
					'name' => 'day',
					'type' => 'text',
					'instructions' => 'Label as \'Day 1\', \'Day 2\', \'Day3\'....',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Day',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_57b93574e9d01',
					'label' => 'Activities',
					'name' => 'activities',
					'type' => 'wysiwyg',
					'instructions' => 'List down the activities for this day',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'visual',
					'toolbar' => 'basic',
					'media_upload' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'summer_camp',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_57b9489a983df',
	'title' => 'Testimony',
	'fields' => array (
		array (
			'key' => 'field_57b948acde134',
			'label' => 'Profile Image',
			'name' => 'profile_image_tes',
			'type' => 'image',
			'instructions' => 'Upload image of the person',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_57b948e5de135',
			'label' => 'Name',
			'name' => 'name_tes',
			'type' => 'text',
			'instructions' => 'Enter the person\'s name',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57b9490ade136',
			'label' => 'Testimony',
			'name' => 'testimony',
			'type' => 'textarea',
			'instructions' => 'Enter the testimony here',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'testimony',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_57d21bd5e7797',
	'title' => 'Theme Settings',
	'fields' => array (
		array (
			'key' => 'field_57d21f5822c59',
			'label' => 'General Settings',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57d21bf5db0b0',
			'label' => 'Welcoming Statement (Front Page)',
			'name' => 'welcoming_statement_front_page',
			'type' => 'text',
			'instructions' => 'Shown on the front page. Default as "Welcome to UPSI Mobility Unit".',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Welcome to UPSI Mobility Unit',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57d21eb1db0b1',
			'label' => 'Opt in query',
			'name' => 'opt_in_query',
			'type' => 'text',
			'instructions' => 'Shown on the front page. Default as "Ready to experience a new culture?"',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Ready to experience a new culture?',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57d21ef0db0b2',
			'label' => 'Register Statement',
			'name' => 'register_statement',
			'type' => 'textarea',
			'instructions' => 'Shown on front page. Default as "Register to find a course, or to keep receiving updates of new courses offered throughout the year."',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Register to find a course, or to keep receiving updates of new courses offered throughout the year.',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => '',
		),
		array (
			'key' => 'field_57d2dc862060a',
			'label' => 'Cards Statement',
			'name' => 'cards_statement',
			'type' => 'textarea',
			'instructions' => 'This statement will appear below the 2 main cards on the front page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'INSTRUCTION: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => '',
		),
		array (
			'key' => 'field_57d225bc78186',
			'label' => 'Summer Camp General (Card)',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57d225e178187',
			'label' => 'Summer Camp Label',
			'name' => 'summer_camp_label',
			'type' => 'text',
			'instructions' => 'Shown on front page. Default as "Summer Camp"',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Summer Camp',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57d2261678188',
			'label' => 'Summer Camp Description',
			'name' => 'summer_camp_description',
			'type' => 'textarea',
			'instructions' => 'Shown on front page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua',
			'placeholder' => '',
			'maxlength' => 120,
			'rows' => '',
			'new_lines' => '',
		),
		array (
			'key' => 'field_57d2545b6febd',
			'label' => 'Summer Card Image',
			'name' => 'summer_card_image',
			'type' => 'image',
			'instructions' => 'Shown on front page, featured on the card.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'hz-card-img',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_57d2449e472fa',
			'label' => 'Exchange Programme General (Card)',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57d244bc472fb',
			'label' => 'Exchange Programme Label',
			'name' => 'exchange_programme_label',
			'type' => 'text',
			'instructions' => 'Shown on front page. Default as "Exchange Programme".',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Exchange Programme',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57d244f1472fc',
			'label' => 'Exchange Programme Description',
			'name' => 'exchange_programme_description',
			'type' => 'textarea',
			'instructions' => 'Shown on front page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'LoLarem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => '',
		),
		array (
			'key' => 'field_57d254ad6febe',
			'label' => 'Exchange Programme Card Image',
			'name' => 'exchange_programme_card_image',
			'type' => 'image',
			'instructions' => 'Shown on front page, featured on the card.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'hz-card-img',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_57d2dde581ba4',
			'label' => 'Welcoming Note',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57d2ddf381ba5',
			'label' => 'Name',
			'name' => 'name',
			'type' => 'text',
			'instructions' => 'Put in the name of the person who is addressing the welcoming note.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Dr. Teng Yan Fang',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57d2de9b81ba6',
			'label' => 'Position',
			'name' => 'position',
			'type' => 'text',
			'instructions' => 'Position of the person who is addressing the welcoming note',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Mobility Unit Coordinator',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57d2ded481ba7',
			'label' => 'The Welcoming Note',
			'name' => 'the_welcoming_note',
			'type' => 'textarea',
			'instructions' => 'Write the welcoming note here.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'It gives me great pleasure to welcome you to Malaysia and thank you for choosing UPSI.

Here , you will learn alongside the current trends of education in research. You will be able to assimilate in a most diverse, multi-cultural settings. Be critical, ask questions and make your voice heard and have lots of fun.

You will be given all the tools and opportunities needed to shape your own future. I encourage you to take advantages of the breath of our University and sign up courses, programs, events. I promise your experience here will be stimulating, exciting and rewarding as possible.',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_57d2df0d81ba8',
			'label' => 'Profile Image',
			'name' => 'profile_image',
			'type' => 'image',
			'instructions' => 'Upload an image of the person who is addressing the welcoming note.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_57e1e74964e2a',
			'label' => 'Featured Course',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57e1e77564e2b',
			'label' => 'Main Featured Course',
			'name' => 'main_featured_course',
			'type' => 'post_object',
			'instructions' => 'Choose only one course to be featured as the MAIN Featured Course on the front page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'summer_camp',
				1 => 'exchange_programmes',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
		),
		array (
			'key' => 'field_57e1e83c64e2c',
			'label' => '3 Sub Featured Courses',
			'name' => '3_sub_featured_courses',
			'type' => 'post_object',
			'instructions' => 'Choose ONLY 3 other courses to be featured on the front page',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'summer_camp',
				1 => 'exchange_programmes',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 1,
			'return_format' => 'object',
			'ui' => 1,
		),
		array (
			'key' => 'field_57d38dd95e8d7',
			'label' => 'Footer Contents',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57d38dec5e8d8',
			'label' => 'Contact Us',
			'name' => 'contact_us',
			'type' => 'textarea',
			'instructions' => 'Insert an address here.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Mobility Unit,
Academic Division,
Universiti Pendidikan Sultan Idris,
35900 Tanjong Malim, Perak, 
Malaysia

Phone Number: XXX-XXXXXXX',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
		),
		array (
			'key' => 'field_57d38f88e124d',
			'label' => 'Twitter Feed',
			'name' => 'twitter_feed',
			'type' => 'text',
			'instructions' => 'Put in your Twitter handle, without the \'@\' here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-general-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_57b94a171b847',
	'title' => 'Trivia',
	'fields' => array (
		array (
			'key' => 'field_57b94a5a0ef6d',
			'label' => 'Trivia Title',
			'name' => 'trivia_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57b94a1a0ef6c',
			'label' => 'The Trivia',
			'name' => 'the_trivia',
			'type' => 'textarea',
			'instructions' => 'Enter the trivia here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'trivia',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;

?>